DROP TABLE IF EXISTS SECTOR;
DROP TABLE IF EXISTS PERSON;

CREATE TABLE PERSON (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  name VARCHAR(250) NOT NULL,
  accepted_terms BOOLEAN DEFAULT FALSE
);

CREATE TABLE SECTOR (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  label VARCHAR(250) NOT NULL,
  value VARCHAR(250) NOT NULL,
  person_id INT NOT NULL,
  constraint sector_person_id_fk foreign key (person_id) REFERENCES PERSON(id)
);